/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CfManagerFactoryInterface extends ethers.utils.Interface {
  functions: {
    "create(address,uint256,uint256,uint256)": FunctionFragment;
    "getInstances()": FunctionFragment;
    "instances(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstances",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "instances",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInstances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "instances", data: BytesLike): Result;

  events: {
    "CfManagerCreated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CfManagerCreated"): EventFragment;
}

export class CfManagerFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CfManagerFactoryInterface;

  functions: {
    create(
      _owner: string,
      _minInvestment: BigNumberish,
      _maxInvestment: BigNumberish,
      _endsAt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getInstances(overrides?: CallOverrides): Promise<[string[]]>;

    instances(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  create(
    _owner: string,
    _minInvestment: BigNumberish,
    _maxInvestment: BigNumberish,
    _endsAt: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getInstances(overrides?: CallOverrides): Promise<string[]>;

  instances(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    create(
      _owner: string,
      _minInvestment: BigNumberish,
      _maxInvestment: BigNumberish,
      _endsAt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getInstances(overrides?: CallOverrides): Promise<string[]>;

    instances(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    CfManagerCreated(
      _cfManager?: null
    ): TypedEventFilter<[string], { _cfManager: string }>;
  };

  estimateGas: {
    create(
      _owner: string,
      _minInvestment: BigNumberish,
      _maxInvestment: BigNumberish,
      _endsAt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getInstances(overrides?: CallOverrides): Promise<BigNumber>;

    instances(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create(
      _owner: string,
      _minInvestment: BigNumberish,
      _maxInvestment: BigNumberish,
      _endsAt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getInstances(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    instances(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
