/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface GlobalRegistryInterface extends ethers.utils.Interface {
  functions: {
    "assetFactory()": FunctionFragment;
    "auditingProcedures(uint256)": FunctionFragment;
    "cfManagerFactory()": FunctionFragment;
    "issuerFactory()": FunctionFragment;
    "owner()": FunctionFragment;
    "payoutManagerFactory()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setAuditingProcedure(uint256,string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateAssetFactory(address)": FunctionFragment;
    "updateCfManagerFactory(address)": FunctionFragment;
    "updateIssuerFactory(address)": FunctionFragment;
    "updatePayoutManagerFactory(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "assetFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auditingProcedures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cfManagerFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issuerFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutManagerFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuditingProcedure",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAssetFactory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCfManagerFactory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIssuerFactory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePayoutManagerFactory",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "assetFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auditingProcedures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cfManagerFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payoutManagerFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuditingProcedure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAssetFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCfManagerFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIssuerFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePayoutManagerFactory",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class GlobalRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GlobalRegistryInterface;

  functions: {
    assetFactory(overrides?: CallOverrides): Promise<[string]>;

    auditingProcedures(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    cfManagerFactory(overrides?: CallOverrides): Promise<[string]>;

    issuerFactory(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    payoutManagerFactory(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuditingProcedure(
      categoryId: BigNumberish,
      ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateAssetFactory(
      newAssetFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateCfManagerFactory(
      newCfManagerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateIssuerFactory(
      newIssuerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updatePayoutManagerFactory(
      newPayoutManagerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  assetFactory(overrides?: CallOverrides): Promise<string>;

  auditingProcedures(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  cfManagerFactory(overrides?: CallOverrides): Promise<string>;

  issuerFactory(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  payoutManagerFactory(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuditingProcedure(
    categoryId: BigNumberish,
    ipfsHash: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateAssetFactory(
    newAssetFactory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateCfManagerFactory(
    newCfManagerFactory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateIssuerFactory(
    newIssuerFactory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updatePayoutManagerFactory(
    newPayoutManagerFactory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    assetFactory(overrides?: CallOverrides): Promise<string>;

    auditingProcedures(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    cfManagerFactory(overrides?: CallOverrides): Promise<string>;

    issuerFactory(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    payoutManagerFactory(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setAuditingProcedure(
      categoryId: BigNumberish,
      ipfsHash: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAssetFactory(
      newAssetFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateCfManagerFactory(
      newCfManagerFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateIssuerFactory(
      newIssuerFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePayoutManagerFactory(
      newPayoutManagerFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    assetFactory(overrides?: CallOverrides): Promise<BigNumber>;

    auditingProcedures(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cfManagerFactory(overrides?: CallOverrides): Promise<BigNumber>;

    issuerFactory(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    payoutManagerFactory(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuditingProcedure(
      categoryId: BigNumberish,
      ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateAssetFactory(
      newAssetFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateCfManagerFactory(
      newCfManagerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateIssuerFactory(
      newIssuerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updatePayoutManagerFactory(
      newPayoutManagerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assetFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    auditingProcedures(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cfManagerFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    issuerFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payoutManagerFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuditingProcedure(
      categoryId: BigNumberish,
      ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateAssetFactory(
      newAssetFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateCfManagerFactory(
      newCfManagerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateIssuerFactory(
      newIssuerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updatePayoutManagerFactory(
      newPayoutManagerFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
