/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IAssetInterface extends ethers.utils.Interface {
  functions: {
    "approveCampaign(address)": FunctionFragment;
    "changeOwnership(address)": FunctionFragment;
    "claimLiquidationShare(address,address)": FunctionFragment;
    "convertFromMirrored()": FunctionFragment;
    "finalizeSale(uint256,uint256)": FunctionFragment;
    "getCampaignRecords()": FunctionFragment;
    "getDecimals()": FunctionFragment;
    "getInfoHistory()": FunctionFragment;
    "getSellHistory()": FunctionFragment;
    "getState()": FunctionFragment;
    "liquidate()": FunctionFragment;
    "setInfo(string)": FunctionFragment;
    "setIssuerStatus(bool)": FunctionFragment;
    "setMirroredToken(address)": FunctionFragment;
    "setWhitelistRequiredForTransfer(bool)": FunctionFragment;
    "snapshot()": FunctionFragment;
    "suspendCampaign(address)": FunctionFragment;
    "totalShares()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approveCampaign",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimLiquidationShare",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "convertFromMirrored",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeSale",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInfoHistory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSellHistory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getState", values?: undefined): string;
  encodeFunctionData(functionFragment: "liquidate", values?: undefined): string;
  encodeFunctionData(functionFragment: "setInfo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setIssuerStatus",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMirroredToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistRequiredForTransfer",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "snapshot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "suspendCampaign",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "approveCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimLiquidationShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertFromMirrored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInfoHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIssuerStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMirroredToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistRequiredForTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "snapshot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "suspendCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;

  events: {};
}

export class IAsset extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAssetInterface;

  functions: {
    approveCampaign(
      campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimLiquidationShare(
      campaign: string,
      investor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    convertFromMirrored(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    finalizeSale(
      tokenAmount: BigNumberish,
      tokenValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCampaignRecords(
      overrides?: CallOverrides
    ): Promise<
      [([string, boolean] & { wallet: string; whitelisted: boolean })[]]
    >;

    getDecimals(overrides?: CallOverrides): Promise<[BigNumber]>;

    getInfoHistory(
      overrides?: CallOverrides
    ): Promise<
      [([string, BigNumber] & { info: string; timestamp: BigNumber })[]]
    >;

    getSellHistory(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, BigNumber, BigNumber] & {
          cfManager: string;
          tokenAmount: BigNumber;
          tokenValue: BigNumber;
          timestamp: BigNumber;
        })[]
      ]
    >;

    getState(
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          string,
          string,
          string,
          string,
          BigNumber,
          boolean,
          boolean,
          string,
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          id: BigNumber;
          contractAddress: string;
          createdBy: string;
          owner: string;
          mirroredToken: string;
          initialTokenSupply: BigNumber;
          whitelistRequiredForTransfer: boolean;
          assetApprovedByIssuer: boolean;
          issuer: string;
          info: string;
          name: string;
          symbol: string;
          totalAmountRaised: BigNumber;
          totalTokensSold: BigNumber;
          liquidated: boolean;
          liquidationTimestamp: BigNumber;
          liquidationSnapshotId: BigNumber;
          liquidationFundsClaimed: BigNumber;
        }
      ]
    >;

    liquidate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setInfo(
      info: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setIssuerStatus(
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMirroredToken(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWhitelistRequiredForTransfer(
      whitelistRequiredForTransfer: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    snapshot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    suspendCampaign(
      campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalShares(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  approveCampaign(
    campaign: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimLiquidationShare(
    campaign: string,
    investor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  convertFromMirrored(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  finalizeSale(
    tokenAmount: BigNumberish,
    tokenValue: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCampaignRecords(
    overrides?: CallOverrides
  ): Promise<([string, boolean] & { wallet: string; whitelisted: boolean })[]>;

  getDecimals(overrides?: CallOverrides): Promise<BigNumber>;

  getInfoHistory(
    overrides?: CallOverrides
  ): Promise<([string, BigNumber] & { info: string; timestamp: BigNumber })[]>;

  getSellHistory(
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, BigNumber, BigNumber] & {
      cfManager: string;
      tokenAmount: BigNumber;
      tokenValue: BigNumber;
      timestamp: BigNumber;
    })[]
  >;

  getState(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      string,
      string,
      BigNumber,
      boolean,
      boolean,
      string,
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      id: BigNumber;
      contractAddress: string;
      createdBy: string;
      owner: string;
      mirroredToken: string;
      initialTokenSupply: BigNumber;
      whitelistRequiredForTransfer: boolean;
      assetApprovedByIssuer: boolean;
      issuer: string;
      info: string;
      name: string;
      symbol: string;
      totalAmountRaised: BigNumber;
      totalTokensSold: BigNumber;
      liquidated: boolean;
      liquidationTimestamp: BigNumber;
      liquidationSnapshotId: BigNumber;
      liquidationFundsClaimed: BigNumber;
    }
  >;

  liquidate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setInfo(
    info: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setIssuerStatus(
    status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMirroredToken(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWhitelistRequiredForTransfer(
    whitelistRequiredForTransfer: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  snapshot(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  suspendCampaign(
    campaign: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalShares(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    approveCampaign(campaign: string, overrides?: CallOverrides): Promise<void>;

    changeOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>;

    claimLiquidationShare(
      campaign: string,
      investor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    convertFromMirrored(overrides?: CallOverrides): Promise<void>;

    finalizeSale(
      tokenAmount: BigNumberish,
      tokenValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getCampaignRecords(
      overrides?: CallOverrides
    ): Promise<
      ([string, boolean] & { wallet: string; whitelisted: boolean })[]
    >;

    getDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    getInfoHistory(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber] & { info: string; timestamp: BigNumber })[]
    >;

    getSellHistory(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, BigNumber] & {
        cfManager: string;
        tokenAmount: BigNumber;
        tokenValue: BigNumber;
        timestamp: BigNumber;
      })[]
    >;

    getState(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        boolean,
        boolean,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        id: BigNumber;
        contractAddress: string;
        createdBy: string;
        owner: string;
        mirroredToken: string;
        initialTokenSupply: BigNumber;
        whitelistRequiredForTransfer: boolean;
        assetApprovedByIssuer: boolean;
        issuer: string;
        info: string;
        name: string;
        symbol: string;
        totalAmountRaised: BigNumber;
        totalTokensSold: BigNumber;
        liquidated: boolean;
        liquidationTimestamp: BigNumber;
        liquidationSnapshotId: BigNumber;
        liquidationFundsClaimed: BigNumber;
      }
    >;

    liquidate(overrides?: CallOverrides): Promise<void>;

    setInfo(info: string, overrides?: CallOverrides): Promise<void>;

    setIssuerStatus(status: boolean, overrides?: CallOverrides): Promise<void>;

    setMirroredToken(token: string, overrides?: CallOverrides): Promise<void>;

    setWhitelistRequiredForTransfer(
      whitelistRequiredForTransfer: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    snapshot(overrides?: CallOverrides): Promise<BigNumber>;

    suspendCampaign(campaign: string, overrides?: CallOverrides): Promise<void>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    approveCampaign(
      campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimLiquidationShare(
      campaign: string,
      investor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    convertFromMirrored(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    finalizeSale(
      tokenAmount: BigNumberish,
      tokenValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCampaignRecords(overrides?: CallOverrides): Promise<BigNumber>;

    getDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    getInfoHistory(overrides?: CallOverrides): Promise<BigNumber>;

    getSellHistory(overrides?: CallOverrides): Promise<BigNumber>;

    getState(overrides?: CallOverrides): Promise<BigNumber>;

    liquidate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setInfo(
      info: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setIssuerStatus(
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMirroredToken(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWhitelistRequiredForTransfer(
      whitelistRequiredForTransfer: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    snapshot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    suspendCampaign(
      campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    approveCampaign(
      campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimLiquidationShare(
      campaign: string,
      investor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    convertFromMirrored(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    finalizeSale(
      tokenAmount: BigNumberish,
      tokenValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCampaignRecords(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDecimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getInfoHistory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSellHistory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    liquidate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setInfo(
      info: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setIssuerStatus(
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMirroredToken(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWhitelistRequiredForTransfer(
      whitelistRequiredForTransfer: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    snapshot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    suspendCampaign(
      campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
