/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IGlobalRegistryInterface extends ethers.utils.Interface {
  functions: {
    "assetFactory()": FunctionFragment;
    "cfManagerFactory()": FunctionFragment;
    "issuerFactory()": FunctionFragment;
    "payoutManagerFactory()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "assetFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cfManagerFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issuerFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payoutManagerFactory",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "assetFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cfManagerFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payoutManagerFactory",
    data: BytesLike
  ): Result;

  events: {};
}

export class IGlobalRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IGlobalRegistryInterface;

  functions: {
    assetFactory(overrides?: CallOverrides): Promise<[string]>;

    cfManagerFactory(overrides?: CallOverrides): Promise<[string]>;

    issuerFactory(overrides?: CallOverrides): Promise<[string]>;

    payoutManagerFactory(overrides?: CallOverrides): Promise<[string]>;
  };

  assetFactory(overrides?: CallOverrides): Promise<string>;

  cfManagerFactory(overrides?: CallOverrides): Promise<string>;

  issuerFactory(overrides?: CallOverrides): Promise<string>;

  payoutManagerFactory(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    assetFactory(overrides?: CallOverrides): Promise<string>;

    cfManagerFactory(overrides?: CallOverrides): Promise<string>;

    issuerFactory(overrides?: CallOverrides): Promise<string>;

    payoutManagerFactory(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    assetFactory(overrides?: CallOverrides): Promise<BigNumber>;

    cfManagerFactory(overrides?: CallOverrides): Promise<BigNumber>;

    issuerFactory(overrides?: CallOverrides): Promise<BigNumber>;

    payoutManagerFactory(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    assetFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cfManagerFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    issuerFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payoutManagerFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
