/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IIssuerInterface extends ethers.utils.Interface {
  functions: {
    "getAssets()": FunctionFragment;
    "getCfManagers()": FunctionFragment;
    "info()": FunctionFragment;
    "isWalletApproved(address)": FunctionFragment;
    "stablecoin()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getAssets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCfManagers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "info", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isWalletApproved",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getAssets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCfManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWalletApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;

  events: {};
}

export class IIssuer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IIssuerInterface;

  functions: {
    getAssets(overrides?: CallOverrides): Promise<[string[]]>;

    getCfManagers(overrides?: CallOverrides): Promise<[string[]]>;

    info(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isWalletApproved(
      _wallet: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    stablecoin(overrides?: CallOverrides): Promise<[string]>;
  };

  getAssets(overrides?: CallOverrides): Promise<string[]>;

  getCfManagers(overrides?: CallOverrides): Promise<string[]>;

  info(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isWalletApproved(
    _wallet: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  stablecoin(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getAssets(overrides?: CallOverrides): Promise<string[]>;

    getCfManagers(overrides?: CallOverrides): Promise<string[]>;

    info(overrides?: CallOverrides): Promise<string>;

    isWalletApproved(
      _wallet: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    stablecoin(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getAssets(overrides?: CallOverrides): Promise<BigNumber>;

    getCfManagers(overrides?: CallOverrides): Promise<BigNumber>;

    info(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isWalletApproved(
      _wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stablecoin(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAssets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCfManagers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    info(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isWalletApproved(
      _wallet: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stablecoin(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
