/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICfManager, ICfManagerInterface } from "../ICfManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_assetAddress",
        type: "address",
      },
    ],
    name: "setAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICfManager__factory {
  static readonly abi = _abi;
  static createInterface(): ICfManagerInterface {
    return new utils.Interface(_abi) as ICfManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICfManager {
    return new Contract(address, _abi, signerOrProvider) as ICfManager;
  }
}
