/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICfManagerSoftcap,
  ICfManagerSoftcapInterface,
} from "../ICfManagerSoftcap";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "changeOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
    ],
    name: "claims",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getInfoHistory",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "info",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct Structs.InfoEntry[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getState",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "contractAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "createdBy",
            type: "address",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "address",
            name: "issuer",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "softCap",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minInvestment",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxInvestment",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "whitelistRequired",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "finalized",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "cancelled",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "totalClaimableTokens",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalInvestorsCount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalClaimsCount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalFundsRaised",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "info",
            type: "string",
          },
        ],
        internalType: "struct Structs.CfManagerSoftcapState",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
    ],
    name: "investments",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "info",
        type: "string",
      },
    ],
    name: "setInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICfManagerSoftcap__factory {
  static readonly abi = _abi;
  static createInterface(): ICfManagerSoftcapInterface {
    return new utils.Interface(_abi) as ICfManagerSoftcapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICfManagerSoftcap {
    return new Contract(address, _abi, signerOrProvider) as ICfManagerSoftcap;
  }
}
