/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICfManagerFactory,
  ICfManagerFactoryInterface,
} from "../ICfManagerFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_minInvestment",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxInvestment",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_endsAt",
        type: "uint256",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getInstances",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICfManagerFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ICfManagerFactoryInterface {
    return new utils.Interface(_abi) as ICfManagerFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICfManagerFactory {
    return new Contract(address, _abi, signerOrProvider) as ICfManagerFactory;
  }
}
