/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC20Snapshot,
  IERC20SnapshotInterface,
} from "../IERC20Snapshot";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "snapshotId",
        type: "uint256",
      },
    ],
    name: "balanceOfAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC20Snapshot__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20SnapshotInterface {
    return new utils.Interface(_abi) as IERC20SnapshotInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20Snapshot {
    return new Contract(address, _abi, signerOrProvider) as IERC20Snapshot;
  }
}
