/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPayoutManagerFactory,
  IPayoutManagerFactoryInterface,
} from "../IPayoutManagerFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "assetAddress",
        type: "address",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getInstances",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPayoutManagerFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPayoutManagerFactoryInterface {
    return new utils.Interface(_abi) as IPayoutManagerFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPayoutManagerFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPayoutManagerFactory;
  }
}
